### ISSUE TITLE
Stíluselem-ötletek összegyűjtése

### ISSUE THREAD

**Issue by pasztor-mark** [pasztor-mark/szteszt-projekt#11]
- Hover effektusok
- Színpaletta
- Kiemelő szín
- Animációk
- Transzformációk
- + minden ami eszetekbe jut

**Comment by BenedekBogardi** [comment]
- Hover: nagyobb box-shadow mögötte, valami más effektus is mehet rá
- Színpaletta: szokásos szürke-fehér
- Kiemelő szín darkslategrey?
- Animációk: főoldalon semmi se kell, majd esetleg ha más oldalnál lesz ötlet szólok
- Transzformációk: szokásos 0.2-0.5s ease-in/ease-out, pl hovernél
- A jövőben valami projekt showcase-re információ display hoveren?
