### ISSUE TITLE
Néhány "céges projekt" készítése

### ISSUE THREAD

**Issue by pasztor-mark** [pasztor-mark/szteszt-projekt#13]
Pl. headline kép a galéria oldalra.

- Kép
- Leírás
- Történet leírás
- Technikai részletek (teljesítmény, stb)

**Comment by BenedekBogardi** [comment]
Vázlatokat elküldtem privátban.
Felülvizsgálhatjátok

**Comment by pasztor-mark** [comment]
Ez igen!
