### ISSUE TITLE
Képek készítése

### ISSUE THREAD

**Issue by Sjosfi** [pasztor-mark/szteszt-projekt#20]

**Comment by pasztor-mark** [comment]
![Image](https://github.com/pasztor-mark/szteszt-projekt/assets/98316698/818ba344-0fb1-4cff-847a-ff25e51c716e)

**Comment by Sjosfi** [comment]
![Image](https://github.com/pasztor-mark/szteszt-projekt/assets/153866645/3eafcfcd-ad8a-42b1-835d-0f33b56beb4c)
![Image](https://github.com/pasztor-mark/szteszt-projekt/assets/153866645/3eca12ad-5f2f-4042-b1d5-8fbec1004dff)
![Image](https://github.com/pasztor-mark/szteszt-projekt/assets/153866645/fae3ba13-454b-4248-87f5-da881d261841)
![Image](https://github.com/pasztor-mark/szteszt-projekt/assets/153866645/4d9e1b5d-ef59-4336-9d37-3e5e1e40df2d)
![Image](https://github.com/pasztor-mark/szteszt-projekt/assets/153866645/8bd1cb09-bf0d-4b67-b446-c88b825720d6)
![Image](https://github.com/pasztor-mark/szteszt-projekt/assets/153866645/162134e9-4478-4518-ae65-739d9aa412f3)

**Comment by pasztor-mark** [comment]
ki ENGEDTE meg neked hogy ELLOPD az ÉN mk5 designomat

**Comment by pasztor-mark** [comment]
új vágás template: 

![Image](https://github.com/pasztor-mark/szteszt-projekt/assets/98316698/7ac2a2e4-7289-40b1-bd53-a29b19c94a4b)
