### ISSUE TITLE
Galéria képleírások készítése

### ISSUE THREAD

**Issue by Sjosfi** [pasztor-mark/szteszt-projekt#24]

**Comment by Sjosfi** [comment]
Holnap iskolában megcsinálom.

**Comment by BenedekBogardi** [comment]
Fiat Abarth 500 1968
Az olasz városi autózás atyja

A már 1957-től gyártott modellt a mai napig, felfrissítve gyártják. Ez nem is véletlen, hiszen a korabeli modellek 500 köbcentis motorja iszonyatosan alacsony fogyasztásra volt képes, akár csak városi közlekedés közben is, emellett kevesebb, mint 3 méteres hosszúsága a parkolást is megkönnyítette. Mindez elég volt ahhoz, hogy a mai napig fennmaradó városi autó lehessen. A mindehhez társított Abarth kiadás pedig vitt egy kis tüzet az autóba, arra az esetre ha a telekre lemennénk hétvégén, élményben is többet nyújtson.

**Comment by BenedekBogardi** [comment]
AMC Javelin 1968
A legamerikaibb izomautó

Az "American Motors Corporation" 1968 és 1971 között gyártotta ezt a lehengerlő formavilágú, szigorú és egyedi izomautót. A 6.6 literes V8-as motor brutális nyomatéka és 300 feletti lőerőszáma valóban egy elképesztő izomautóvá tette a maga korában, emellett árban is elérhető kategória volt. A mai napig időtlen forma, ám sajnos, mint minden más amerikai dögnek, ennek is betett a 70-es évek olajválsága, így a modell feledésbe merült, majd a márka megszűnésével megpecsételődött, hogy nem is tér vissza.
