### ISSUE TITLE
Cég történetének leírása, csapatunkból mindenkiről egy leírás

### ISSUE THREAD

**Issue by BenedekBogardi** [pasztor-mark/szteszt-projekt#29]
Valami sztorit találjunk ki a cégnek, amit leírhatunk a rólunk oldalban.
A projektes csapattagok írjanak egy leírást a saját munkájukról az oldalra.

**Comment by pasztor-mark** [comment]
Idővonalhoz kellene kb 4-5 lépés, benne egy 1-2 szavas cím, és olyan 15-25 szavas leírás

**Comment by Sjosfi** [comment]
**műhely jövője idővonal:**

Műhely népszerűsítése
Szociális médián erősebb jelenlét kiépítése, a műhely népszerűsítése nagyobb célközönség előtt.

Ambiciózusabb projektek elvállalása
Drágábbnál drágább autókkal történő munkák, vagy akár autók felismerhetetlenségig megváltoztatása.

Nagyobb műhelyre váltás
Műhelyünk kibővítése, hogy az eddiginél egyszerre több munkafolyamat történhessen.

Korszerűsítés
Folyamatosan próbálunk a legújabb technológiákkal rendelkezni, legyen az akár elektromos, vagy hasonló környezetbarát autókkal való munka.

Új műhelyek
Országszerte új műhelyek nyitása, ezzel sokkal több ügyfél elérése, ami sokkal több boldog autót jelent.

További terjeszkedés
Más országokban is HuGyoS műhelyek nyitása, nemzetközileg is megtapasztalhatják a boldog ügyfelek kitűnő munkánkat.

**Comment by pasztor-mark** [comment]
Ez igen!
