### ISSUE TITLE
Főoldal felépítése

### ISSUE THREAD

**Issue by pasztor-mark** [pasztor-mark/szteszt-projekt#4]
a kész alapkomponensekkel összerakjuk a főoldalt a tervek szerint

**Comment by pasztor-mark** [comment]
masszív

![Image](https://github.com/pasztor-mark/szteszt-projekt/assets/98316698/96adc7aa-f47d-4620-b092-c45d07119ab8)

ha mindenkinek megfelel commitolom és zárom, bármilyen kérés van szóljatok

**Comment by pasztor-mark** [comment]
+: kösz srácok az anyagokat meg az elrendezést

**Comment by Sjosfi** [comment]
Nagyon jó lesz eddig
