### ISSUE TITLE
Ár oldal arculat tervezés

### ISSUE THREAD

**Issue by pasztor-mark** [pasztor-mark/szteszt-projekt#9]
navbar footer fix, kártyákat designoljátok meg és döntsétek el hogy hány kártya legyen egy sorban
árkártya tulajdonságai: szolgáltatás neve, minimum ár, maximum ár, leírás

**Comment by BenedekBogardi** [comment]
- 4 képkártya egy sorban 
- 2-3 szöveges kártya egy sorban
- Színpaletta maradjon szürkés
- Legyen 1 headline kártya, pl egy éppen aktuális projektről
- Képes kártyák magasabbak, szöveges kártyák inkább szélesek legyenek.
- Méret tulajdonságok [!] egyezzenek

**Comment by pasztor-mark** [comment]
https://www.figma.com/file/ok2bwbG85Ps84fwiUv46QR/Szoftverteszt-Projekt?type=design&node-id=0-1&mode=design&t=AXI27v3PsfzWNGe6-0
